#!/usr/bin/env python3
import sys
import pathlib
import pyuavcan_cli
if __name__ == '__main__':
    sys.path.append(str(pathlib.Path(__file__).absolute().parent.parent.parent))
    pyuavcan_cli.main()
