#
# Copyright (c) 2019 UAVCAN Development Team
# This software is distributed under the terms of the MIT License.
# Author: Pavel Kirienko <pavel.kirienko@zubax.com>
#

import os
import sys
import typing
import pathlib
import argparse
import pyuavcan
import dataclasses


# Base data directory. The location is OS-dependent.
if hasattr(sys, 'getwindowsversion'):
    _appdata_env = os.getenv('LOCALAPPDATA') or os.getenv('APPDATA')
    assert _appdata_env, 'App data directory not found'
    BASE_DATA_DIR = pathlib.Path(_appdata_env, 'UAVCAN', 'PyUAVCAN')
else:
    BASE_DATA_DIR = pathlib.Path('~/.uavcan/pyuavcan').expanduser()

# This path is unique per library version.
VERSION_SPECIFIC_DATA_DIR = BASE_DATA_DIR / f'v{".".join(map(str, pyuavcan.__version__[:2]))}'

# It's version-specific so that we won't attempt to load packages generated by another version.
DEFAULT_DSDL_GENERATED_PACKAGES_DIR = VERSION_SPECIFIC_DATA_DIR / 'dsdl-generated-packages'


@dataclasses.dataclass(frozen=True)
class CommandInfo:
    """
    The name of the Python module (or package) will be used as the primary name of the command with underscores
    replaced with minus characters: "foo_bar.py" --> "foo-bar". Aliases are optional.
    """
    help:     str
    examples: str = ''
    aliases:  typing.Sequence[str] = dataclasses.field(default_factory=list)


def add_argument_local_node_id(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        '--local-node-id', '-L',
        default='naive',
        metavar='INTEGER_OR_DIRECTIVE',
        help='''
Node-ID to use for the requested operation. Could be either a specific integer
value or one of the special values: "pnp" to perform plug-and-play allocation;
"naive" to select the highest node-ID which does not seem to be occupied at
the time when the command is launched.
Default: %(default)s
'''.strip(),
    )


def add_argument_iface(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        '--iface', '-i',
        action='append',
        required=True,
        help='''
Which transport media interface to use.
Specify more than once to use redundant interfaces.
'''.strip(),
    )
