name: Main Workflow

on:
  push:
    branches: [legacy-v0, republish]
  pull_request:
    branches: [legacy-v0]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['2.7', '3.5', '3.6', '3.7']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      
      - name: Install Dependencies
        run: sudo pip install flake8 mock

      #- name: Lint
        #run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test
        run: python -m unittest discover test
