name: Main Workflow

on:
  push:
    branches: [legacy-v0, republish]
  pull_request:
    branches: [legacy-v0]

jobs:
  lint:
    name: Lint and Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7']

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      
      - name: Install Dependencies
        run: sudo pip install flake8 mock

      #- name: Lint
        #run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Test
        run: python -m unittest discover test

  pypi:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        continue-on-error: true # this step will fail if the file has already been published
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN_GLOBAL }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        continue-on-error: true # this step will fail if the file has already been published
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_PYUAVCAN_V0 }}
          verbose: true
